architecture: YOLOv3
use_gpu: true
max_iters: 100000
log_smooth_window: 20
save_dir: output
snapshot_iter: 10000
metric: COCO
#pretrain_weights: https://paddlemodels.bj.bcebos.com/object_detection/ResNet50_vd_obj365_pretrained.tar
pretrain_weights: output/r50_vd_dcn_db
weights: output/omni_r50vd_iouloss_obj365_pretrained/model_final
num_classes: 12
use_fine_grained_loss: true

YOLOv3:
  backbone: ResNet
  yolo_head: YOLOv3Head
  use_fine_grained_loss: true

ResNet:
  norm_type: sync_bn
  freeze_at: 0
  freeze_norm: false
  norm_decay: 0.
  depth: 50
  feature_maps: [3, 4, 5]
  variant: d
  #dcn_v2_stages: [5]

YOLOv3Head:
  anchor_masks: [[6, 7, 8], [3, 4, 5], [0, 1, 2]]
  #anchors: [[10, 13], [16, 30], [33, 23],
  #          [30, 61], [62, 45], [59, 119],
  #          [116, 90], [156, 198], [373, 326]]
  ###v2x 4w
  anchors: [[8, 9], [10, 23], [19, 15],
            [23, 33], [40, 25], [54, 50],
            [101, 80], [139, 145], [253, 224]]
  norm_decay: 0.
  yolo_loss: YOLOv3Loss
  nms:
    background_label: -1
    keep_top_k: 100
    nms_threshold: 0.45
    nms_top_k: 1000
    normalized: false
    score_threshold: 0.01

YOLOv3Loss:
  batch_size: 8
  ignore_thresh: 0.7
  label_smooth: false
  use_fine_grained_loss: true
  #iou_loss: IouLoss

#IouLoss:
#  loss_weight: 2.5
#  max_height: 608
#  max_width: 608

LearningRate:
  base_lr: 0.001
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones:
    - 30000
    - 40000
  - !LinearWarmup
    start_factor: 0.
    steps: 4000

OptimizerBuilder:
  optimizer:
    momentum: 0.9
    type: Momentum
  regularizer:
    factor: 0.0005
    type: L2

_READER_: './omni_reader_track1.yml'
